// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-variants/Feed.tsx": () => import("../components/mockups/dashboard-variants/Feed.tsx"),
  "./components/mockups/dashboard-variants/Gauge.tsx": () => import("../components/mockups/dashboard-variants/Gauge.tsx"),
  "./components/mockups/dashboard-variants/Scorecard.tsx": () => import("../components/mockups/dashboard-variants/Scorecard.tsx")
};
